### ISSUE TITLE
change path for a running shell command (run)

### ISSUE THREAD

**Issue by mgiaco** [pyinvoke/invoke#284] opened 2015-11-08 21:44 UTC
Hi,

Is there a fabric lcd equivalent to change the path? 

``` python
def make():
    with lcd(BUILD_PATH):
        local('make -j4')
```

How can I achieve this with invoke?

thx

**Comment by bitprophet** [comment] 2015-11-09 01:20
Not implemented yet unfortunately. Semi related to #259 insofar as the actual `$PATH` is part of an environment, but that only matters for `run()` if it's invoking a shell (IIRC).

**Comment by bitprophet** [comment] 2015-12-21 23:12
Linking this to the newly created but soon to be fulfilled #293.

**Comment by mgiaco** [comment] 2016-07-07 14:07
Hello,

Today I try to switch to the new version 0.13. Before update to 0.12 this works for me:

code segment from task.py:

```python
@task
def env(ctx):
	os.environ["PATH"] = os.pathsep.join(ctx.path.values()) + os.pathsep + os.environ["PATH"]

@task(env)
def clean(ctx):
	print os.getcwd()
	with chdir('C:/workdir/project/build'):
		print os.getcwd()
		print '"{}" clean'.format(ctx.make.gnu_mingw32_make)
		ctx.run('"{}" clean'.format(ctx.make.gnu_mingw32_make))


@contextlib.contextmanager
def chdir(dirname=None):
  curdir = os.getcwd()
  try:
    if dirname is not None:
      os.chdir(dirname)
    yield
  finally:
    os.chdir(curdir)
```

invoke.py:

```python
path = {
    "gnu_arm": "c:\\Program Files (x86)\\GNU Tools ARM Embedded\\4.9 2015q2\\bin",
    "mingw32": "c:\\msys64\\mingw32\\bin",
    "gnu_arm_tools": "c:\\Program Files\\GNU ARM Eclipse\\Build Tools\\2.6-201507152002\\bin",
}

make = {
    "gnu_arm_make": "{}\\make.exe".format(path["gnu_arm_tools"]),
    "gnu_mingw32_make": "{}\\mingw32-make.exe".format(path["mingw32"]),
}

tools = {
    "doxygen": "c:\\Program Files\\doxygen\\bin\\doxygen.exe",
    "ant_bat": "c:\\ant\\bin\\ant.bat",
}
```

With version 13.0 this does not work anymore.  Do you have any idea how I can fix that?
many thanks

**Comment by bitprophet** [comment] 2016-07-07 21:17
Can you paste the full traceback? Offhand I don't know why 0.13 would have broken your `chdir` stuff. You might be running into some separate Windows bug in 0.13 (there are a few outstanding).

**Comment by mgiaco** [comment] 2016-07-11 06:23
Hello, 

So here is my output. 

```shell
C:\workdir\projekt\build
"c:\msys64\mingw32\bin\mingw32-make.exe" clean
Traceback (most recent call last):
  File "C:\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Envs\py35_invoke\Scripts\inv.exe\__main__.py", line 9, in <module>
  File "C:\Envs\py35_invoke\lib\site-packages\invoke\program.py", line 270, in run
    self.execute()
  File "C:\Envs\py35_invoke\lib\site-packages\invoke\program.py", line 381, in execute
    executor.execute(*self.tasks)
  File "C:\Envs\py35_invoke\lib\site-packages\invoke\executor.py", line 113, in execute
    result = call.task(*args, **call.kwargs)
  File "C:\Envs\py35_invoke\lib\site-packages\invoke\tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "C:\workdir\io6\li_can_slv\tasks.py", line 44, in clean
    ctx.run('"{}" clean'.format(ctx.make.gnu_mingw32_make))
  File "C:\Envs\py35_invoke\lib\site-packages\invoke\context.py", line 53, in run
    return runner_class(context=self).run(command, **kwargs)
  File "C:\Envs\py35_invoke\lib\site-packages\invoke\runners.py", line 259, in run
    self.start(command, shell, env)
  File "C:\Envs\py35_invoke\lib\site-packages\invoke\runners.py", line 966, in start
    stdin=PIPE,
  File "C:\Python35\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden

(py35_invoke) C:\workdir\projekt\build>
```

So as you can see it is a simple call to 

``` shell
"c:\msys64\mingw32\bin\mingw32-make.exe" clean
```

Thanks for the help

**Comment by bitprophet** [comment] 2016-07-20 01:09
Hmm, I'm wondering if #259 - which was included in 0.13 - is the cause of this. It changes the subprocess invocation (both variants) to use an explicit environment, which is based on `os.environ`.

So if `os.environ` is preserving the value of `PWD` (or the Windows equivalent), and `os.chdir` is not updating `os.environ` (the docs for `os.environ` specifically state that it is not live-updated, so this is probably the case), it's possible that whatever `os.chdir` does (on Windows, at least, if not on all platforms) is being effectively discarded by us handing the "new" env to `subprocess`.

@mgiaco You can probably test this by modifying your local Invoke install to revert the `env=env` bit in the `subprocess` call in `invoke/runners.py` - I'd be curious to see if that 'fixes' the problem for you.

If it does, we'll probably have to add an FAQ about this & update priority of this ticket's feature request. We'd need our own directory-changing method(s) that alters `os.environ` or otherwise updates the subprocess calls (both variants, as always) so that their 'cwd' is the same as `os.getcwd()`.

**Comment by mgiaco** [comment] 2016-07-20 08:16
So I do not know exactly what you mean with revert the env=env bit in the subprocess call in invoke/runners.py - I'd be curious to see if that 'fixes' the problem for you. Should I diff with version 0.12.0 here?

**Comment by mgiaco** [comment] 2016-07-21 11:30
Hello,

Okay that was what I tried. But I get the same error. 

Here is my task.py

```python

from invoke import Collection
from invoke import run, config, task
import os
import contextlib

BUILD_PATH = 'build'

@task
def env(ctx):
    os.environ["PATH"] = os.pathsep.join(ctx.path.values()) + os.pathsep + os.environ["PATH"]

@task(env)
def clean(ctx):
    print(os.getcwd())
    with chdir('C:/tmp/build'):
        print(os.getcwd())
        print('"{}" clean'.format(ctx.make.gnu_mingw32_make))
        ctx.run('"{}" clean'.format(ctx.make.gnu_mingw32_make))


@contextlib.contextmanager
def chdir(dirname=None):
  curdir = os.getcwd()
  try:
    if dirname is not None:
      os.chdir(dirname)
    yield
  finally:
    os.chdir(curdir)

```

here my invoke.py:

```python
path = {
    "gnu_arm": "c:\\Program Files (x86)\\GNU Tools ARM Embedded\\4.9 2015q2\\bin",
    "mingw32": "c:\\msys64\\mingw32\\bin",
    "gnu_arm_tools": "c:\\Program Files\\GNU ARM Eclipse\\Build Tools\\2.6-201507152002\\bin",
}

make = {
    "gnu_arm_make": "{}\\make.exe".format(path["gnu_arm_tools"]),
    "gnu_mingw32_make": "{}\\mingw32-make.exe".format(path["mingw32"]),
}

tools = {
    "doxygen": "c:\\Program Files\\doxygen\\bin\\doxygen.exe",
    "ant_bat": "c:\\ant\\bin\\ant.bat",
}
```

Add a Folder on C:/tmp/build and then you/or someone should also get the error. So maybe someone could test it who is more familiar with the invoke implementation.

It would be really great if someone can check that.

**Comment by mgiaco** [comment] 2016-09-01 14:43
Are there any news here?

**Comment by jrmi** [comment] 2016-10-08 13:29
I've done a workaround if it's can help someone:

```python
class CustomRunner(Local):
    def __init__(self, context):
        self.prefix = context.config.get('prefix', '')
        self.postfix = context.config.get('postfix', '')
        super(CustomRunner, self).__init__(context)

    def start(self, command, shell, env):
        super(CustomRunner, self).start(self.prefix + command + self.postfix, shell,  env)

@contextmanager
def prefix(ctx, prefix='', postfix=''):
    prefix_orig = ctx.config.get('prefix', '')
    postfix_orig = ctx.config.get('postfix', '')
    prefix = prefix + prefix_orig
    postfix = postfix_orig + postfix
    try:
        ctx.config['prefix'] = prefix
        ctx.config['postfix'] = postfix
        yield
    finally:
        ctx.config['prefix'] = prefix_orig
        ctx.config['postfix'] = postfix_orig

@contextmanager
def cd(ctx, path):
    # cd only use prefix
    with prefix(ctx, "cd %s && " % path):
        yield

@task
def test(ctx):
    with cd(ctx, "new/path"):
        ctx.run('ls')

ns = Collection(test)
ns.configure({'runner': CustomRunner})
```

First I define a custom `runner` that I make default in last line with `ns.configure` line. This custom `runner` can add  `prefix` and `suffix` from `config` to command.
Then I create a `contextmanager` that add  `"cd <path> &&"` prefix and use it in the task.

This also work if you want to load a virtualenv with a code like:
```python

@contextmanager
def virtualenv(ctx, venv_path):
    with prefix(ctx, ". %s/bin/activate && " % venv_path):
        yield
```

and sudo command with (I know it's included but doesn't works for me...):

```python
@contextmanager
def as_root(ctx):
    with prefix(ctx, "sudo sh -c \" ", "\""):
        yield
```
And you can combine all of this (order is important):

```python
@task
def test(ctx):
    with cd(ctx, "/tmp"), virtualenv(ctx, "~/.virtualenvs/myVenv"), as_root(ctx):
        # next commands are executed as_root in myVenv in dir /tmp.
        ctx.run('whoami')
        ctx.run('pwd')
        ctx.run('which python')
```
I think you can do other things...

The problem is that I'm not shure this is thread safe...

**Comment by bitprophet** [comment] 2017-06-02 18:37
#446 got this! (Also this was a duplicate of #230, apparently. Whoops.)

**Closed by bitprophet** 2017-06-02 18:37 UTC
Labels: Feature, Needs patch

**Comment by mgiaco** [comment] 2017-06-03 13:24
So this is fixed now? Nice. Is there any sample around how I can use that.
cheers
mathias

**Comment by bitprophet** [comment] 2017-06-05 17:49
@mgiaco API doc is here: http://docs.pyinvoke.org/en/0.18.0/api/context.html#invoke.context.Context.cd

**Comment by mgiaco** [comment] 2017-06-05 19:28
Wow many thanks, that looks so great I will give it a try tomorrow at my office.
thx

**Comment by jrmi** [comment] 2017-06-06 07:05
Good news ! And we now have new opportunities to extend invoke.

**Comment by mgiaco** [comment] 2017-06-07 15:56
hey, so today I tried with python 3.5 and the latest invoke 0.18 this on a working directory with git.
Running on a windows 7 x64 host. python is also x64

```python

from invoke import task


@task
def diff(ctx):
    with ctx.cd('.//'):
        ctx.run('git difftool --dir-diff')


@task
def add_submodules(ctx):
    print("repo root... ")


@task
def test(ctx):
    with ctx.cd('c:\\'):
        print(ctx.cwd)
```


No i try to do a `inv diff`  with this result:

```shell

Traceback (most recent call last):
  File "C:\Python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Envs\py35\Scripts\inv.exe\__main__.py", line 9, in <module>
  File "c:\envs\py35\lib\site-packages\invoke\program.py", line 285, in run
    self.execute()
  File "c:\envs\py35\lib\site-packages\invoke\program.py", line 400, in execute
    executor.execute(*self.tasks)
  File "c:\envs\py35\lib\site-packages\invoke\executor.py", line 132, in execute
    result = call.task(*args, **call.kwargs)
  File "c:\envs\py35\lib\site-packages\invoke\tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "C:\Boot\tasks.py", line 7, in diff
    ctx.run('git difftool --dir-diff')
  File "c:\envs\py35\lib\site-packages\invoke\context.py", line 87, in run
    return self._runner.run(command, **kwargs)
  File "c:\envs\py35\lib\site-packages\invoke\runners.py", line 259, in run
    return self._run_body(command, **kwargs)
  File "c:\envs\py35\lib\site-packages\invoke\runners.py", line 273, in _run_body
    self.start(command, shell, env)
  File "c:\envs\py35\lib\site-packages\invoke\runners.py", line 989, in start
    stdin=PIPE,
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden

(py35) C:\Boot>

````

So I do not know what I am doing wrong here, because a normal git difftool ... works perfect.

**Comment by mgiaco** [comment] 2017-06-07 15:57
Also this doese not work:

```
@task
def diff(ctx):
    ctx.run('git difftool --dir-diff')
```

**Comment by mgiaco** [comment] 2017-06-21 09:33
Hi, today I tried this little example:

```python
from invoke import task, run, context
import os

@task
def test(ctx):
	print(os.getcwd())
	with ctx.cd('../'):
		print(os.getcwd())
		print('test')

```

output: 

```shell

(py35_invoke) c:\workdir\io6\invoke_test>inv test
c:\workdir\io6\invoke_test
Traceback (most recent call last):
  File "e:\github_python\invoke\invoke\config.py", line 69, in __getattr__
    return self._get(key)
  File "e:\github_python\invoke\invoke\config.py", line 113, in _get
    value = self.config[key]
  File "e:\github_python\invoke\invoke\config.py", line 110, in __getitem__
    return self._get(key)
  File "e:\github_python\invoke\invoke\config.py", line 113, in _get
    value = self.config[key]
KeyError: 'cd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lwngim1\Envs\py35_invoke\Scripts\inv.exe\__main__.py", line 9, in <module>
  File "e:\github_python\invoke\invoke\program.py", line 270, in run
    self.execute()
  File "e:\github_python\invoke\invoke\program.py", line 381, in execute
    executor.execute(*self.tasks)
  File "e:\github_python\invoke\invoke\executor.py", line 113, in execute
    result = call.task(*args, **call.kwargs)
  File "e:\github_python\invoke\invoke\tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "c:\workdir\io6\invoke_test\tasks.py", line 7, in test
    with ctx.cd('../'):
  File "e:\github_python\invoke\invoke\config.py", line 81, in __getattr__
    raise AttributeError(err)
AttributeError: No attribute or config key found for 'cd'

Valid keys: ['run', 'tasks']

Valid real attributes: ['from_data', 'run']
```

**Comment by bitprophet** [comment] 2017-06-21 14:09
@mgiaco are you sure you've got Invoke 0.18 or newer?

**Comment by mgiaco** [comment] 2017-06-21 16:20
Hey yes I am really sure but I will check it tomorrow for a second time.

**Comment by mgiaco** [comment] 2017-06-22 11:28
So today I installed python3.6 with invoke 0.19 now it works. But I can say with python 3.5.1 and invoke 0.19 it does not work.
