### ISSUE TITLE
Input disappears on Mac OSX El Capitan when cancelling a task

### ISSUE THREAD

**Issue by thedrow** [pyinvoke/invoke#323] opened 2016-02-06 13:50 UTC
When I cancel a task in iTerminal2 while it's running a subprocess using `run()` the input disappears.
You can still type but you wont see the characters anymore.
Using `stty echo` restores input visibility.
I have not tested this elsewhere. This is on invoke 0.12.1 and PyPy 4.0.1.

**Comment by bitprophet** [comment] 2016-02-08 02:55
This sounds like a dupe of #303 which just got fixed - thanks!

**Closed by bitprophet** 2016-02-08 02:55 UTC
