### ISSUE TITLE
no input echo after running with pty=True

### ISSUE THREAD

**Issue by Eraldo** [pyinvoke/invoke#307] opened 2016-01-17 18:51 UTC
When I issue a command with pty=True

Example: run('./manage.py createsuperuser', pty=True)

Running it without the pty=True does not give me an interactive session. That is why I use it.

The command itself works nicely.. but after stopping it (ctrl-c) I do not see what I am typing anymore.
Only when I press return do I see what I typed and if it was correct.

Any ideas on how to fix that?

Feel free to ask for further context. :D

**Comment by tuukkamustonen** [comment] 2016-01-18 09:27
Looks like duplicate of https://github.com/pyinvoke/invoke/issues/303 ?

**Comment by Eraldo** [comment] 2016-01-18 10:35
@tuukkamustonen yes.. it is the same issue. Was not aware of #303.
I have subscribed it - thank you.

**Closed** 2016-01-20 21:18 UTC
