### ISSUE TITLE
Is there a way to debug a task.py specific taks?

### ISSUE THREAD

**Issue by mgiaco** [pyinvoke/invoke#545] opened 2018-06-27 12:54 UTC
Hi,

Normally I use pycharm is there a way to debug task.py via the python debugger?

many thanks

**Comment by bitprophet** [comment] 2018-06-28 00:11
There shouldn't be anything getting in the way of usual debugging tactics here, can you post whatever trouble you're having? Afraid I'm not an IDE user so not quite sure how they like to be set up.

Gonna close this as "not a bug, just a discussion". thanks!

**Closed by bitprophet** 2018-06-28 00:11 UTC

**Comment by mgiaco** [comment] 2018-06-28 06:45
Okay that´s fine.  So I do have a task.py and I want to debug a specific task which I wrote inside that task.py.
So my question was is there a way to start the python debugger in any way on a line like:

inv mytask

**Comment by bitprophet** [comment] 2018-07-05 19:10
You should be able to use debuggers normally, such as inside the top of the task body, eg:

```
@task                            
def foo(c):                      
    import pdb; pdb.set_trace()  
    print('hi')                  
```

and then

```
» inv foo
> /Users/jforcier/Code/oss/invoke/tasks.py(77)foo()
-> print('hi')
(Pdb) 
```

**Comment by mgiaco** [comment] 2018-07-09 10:40
Okay many thanks, but how to start that debugging session?

**Comment by KapuKapu** [comment] 2021-09-20 08:55
1. Add an new Configuration with: Run -> Edit Configurations -> + -> Python
2. Fill out "Script path", "Parameters" and "Working directory" like in the image below
3. Debug it

![pycharm_invoke_debug](https://user-images.githubusercontent.com/1653690/133976769-084e988a-fe43-405d-b270-5827631e06ec.png)

**Comment by ernstki** [comment] 2026-05-18 17:12
For the console lovers:

```console
$ python -m pdb -m invoke <task-name>
> /path/to/my/venv/lib/python3.x/site-packages/invoke/__main__.py(1)<module>()
-> from invoke.main import program
(Pdb)
```

This seems useful and important, and yet I see no mention of this (or `INVOKE_DEBUG=1`) in the README or [in](https://www.pyinvoke.org/search.html?q=debug) [the](https://www.pyinvoke.org/search.html?q=invoke_debug) [docs](https://docs.pyinvoke.org/en/stable/search.html?q=debug), except perhaps tangentially in the changelog.

Is this something All Python People Should Just Know, or does it merit a documentation PR? (which I'd be willing to do)

**Edit**: I guess `INVOKE_DEBUG=1` is probably the same as `--debug` which is documented in the `--help`, so that's something.
