### ISSUE TITLE
pty-bearing subprocesses always appear to be 80x24, which stinks for interactive work

### ISSUE THREAD

**Issue by matleh** [pyinvoke/invoke#216] opened 2015-03-10 09:18 UTC
I have a invoke task, that enters a docker container in interactive mode. Basically, it does

```
ctx.run("docker start -it ubuntu bash", pty=True)
```

But inside that, the terminal is not really usable. `tput cols` and `tput lines` return default values of 80 and 24, but really these should be like 195 and 70. As a consequence, many commands like _less_ or _top_ or even bash line editing become unusable.

When I run the docker command directly (not through invoke) everything works as expected.

This can be reproduced with

``` python
from invoke import ctask

ctask
def foo(ctx):
   ctx.run("bash -c 'tput cols; tput lines'", pty=True)
```

will output `80\n24` no matter what size the surrounding terminal window is.

Is there some additional initialisation of the pty needed?

**Comment by sophacles** [comment] 2015-03-10 15:31
I've reproduced @matleh's test case issue on my Mac in a term window of various sizes. 

I've noticed in the past that there are strange pty things associated with docker as well, but those have been with and without inv in the loop. Irrespective of that, the term size an issue.

In pexpect there are the `getwinsize` and `setwinsize` methods to the `spawn` class- and they don't appear to be used unless the calling program does so. Also note that there are some issues with cygwin (and maybe others) mentioned in the comments and docstrings of the pexpect module.

**Comment by sophacles** [comment] 2015-03-10 18:20
Quick update: a thought struck me to check term windows with a size *smaller* than 80x24, and in that case the size is still reported as 80x24 as well.

**Comment by bitprophet** [comment] 2015-03-10 20:52
I was going to say something may be buggy in https://github.com/pyinvoke/invoke/blob/89e147e80b8c955c835115c32b283b750f3452c8/invoke/platform.py#L18-L60 but then I checked and we only use that for our own "print stuff to terminal & format appropriately" code (e.g. `inv --list`).

So I checked pexpect because that's what runs `pty=True` commands, and sho nuff: https://github.com/pyinvoke/invoke/blob/89e147e80b8c955c835115c32b283b750f3452c8/invoke/vendor/pexpect.py#L566

I'm hoping that we can just drop something like `p.setwinsize(*pty_size())` or similar, after this line: https://github.com/pyinvoke/invoke/blob/89e147e80b8c955c835115c32b283b750f3452c8/invoke/runner.py#L132 and that would work? Have not tried yet myself.

**Comment by frol** [comment] 2015-09-03 16:23
@matleh How about
```python
ctx.run("docker run -it ubuntu bash -i")
```
? (The trick is `-i` option to bash)

This works for me.

**Comment by susu** [comment] 2016-03-07 11:59
I also have this problem, "bash -i" did not help. Any updates on this?

**Comment by frol** [comment] 2016-04-14 08:13
Here is my workaround using `pexpect` instead of `run(pty=True)`:

BEFORE

```python
context.run(run_command, pty=True)
```

AFTER

```python
def _run_with_pty(context, command):
    """
    This helper workarounds lack of complete PTY support in Invoke:
    https://github.com/pyinvoke/invoke/issues/216
    """
    import pexpect
    import signal
    from invoke.exceptions import Failure
    from invoke.platform import pty_size
    from invoke.runners import Result
    
    def autoupdate_pty_size(pexpect_process):
        def update_pty_size(sig, data):
            pexpect_process.setwinsize(*pty_size()[::-1])
        signal.signal(signal.SIGWINCH, update_pty_size)
        update_pty_size(None, None)

    command_process = pexpect.spawn(context['run'].shell, ['-c', command])
    autoupdate_pty_size(command_process)

    command_process.interact()
    
    command_result = Result(
        command=command,
        shell=context['run'].shell,
        env=None,
        stdout=command_process.read(),
        stderr=None,
        exited=command_process.exitstatus,
        pty=True
    )
    if not command_result:
        raise Failure(command_result)
    return command_result

_run_wuth_pty(context, run_command)
 ```

**Comment by svetlyak40wt** [comment] 2016-04-21 12:14
@frol thank you for the snippet with workaround. It works for me with a little change. I use `getattr(context['run'], 'shell', 'bash')` instead of `context['run'].shell`.

**Comment by iago1460** [comment] 2016-11-29 14:11
@frol Thanks, the workaround seems working

**Comment by bitprophet** [comment] 2018-07-31 02:50
This issue's a bit old and I'm wondering if it's been incidentally fixed in the interim:

- Invoke 1.0.x and I can (macOS 10.12, Python 3.6.4) do eg `run("vim", pty=True)` inside a 154x41 tmux pane no problem; can edit all the way up to the 154th-or-so column, and so forth. Even running `:!stty size` inside that vim shows the right dimensions in the subprocess' shell.
- So at least as of 1.0, we're transmitting the data correctly. Changelog mentions us doing so in 0.11.x, which would have come out before this ticket was filed, so not sure what's up with that.
- Figured maybe this was some bizarre interaction between Invoke and Docker (or at least something Docker happens to be doing re: terminals and pipes) but then I remembered I have some private tiny tasks file specifically for managing my own local containers, which does `ctx.run("docker run -it ...", pty=True)` all day long with no apparent problems.

So I'm guessing this is solved now and will close as "can no longer reproduce"...if anyone _can_ still reproduce this with Invoke 1.0 or up, please comment!

**Closed by bitprophet** 2018-07-31 02:50 UTC
Labels: Bug, run()

**Comment by russkel** [comment] 2021-07-14 11:26
@bitprophet  This seems to be happening again. I do a `ctx.run("docker run -it ...", pty=True) ` and then `stty size` seems to be correct initially, but I then resize the terminal (kitty) and run the command again, and it reports the same size.
I ran the same command without invoke in a terminal, and did the same test, each time the terminal kept the correct size.

**Comment by bitprophet** [comment] 2021-07-23 18:39
Sounds like missing SIGWINCH support, which ironically ISTR implementing recently...in Fabric! I'd guess we could repackage that upstream here and re-execute the `fcntl.ioctl` bits we run at startup (makes the inner PTY for the subprocess match the current size of the invoking terminal) where in Fabric we call a specific window change SSH command.

EDIT: in fact that's also recommended upthread, clearly I overlooked it last time I read this over (as it's not technically the same as the original complaint). The signal.signal approach is exactly what Fabric did. I'll make a new ticket for this for clarity.

**Comment by russkel** [comment] 2021-07-24 02:40
Thanks @bitprophet
