### ISSUE TITLE
Invoke Handles Readline Rather Oddly

### ISSUE THREAD

**Issue by hjc1710** [pyinvoke/invoke#361] opened 2016-06-16 23:21 UTC
So, this one is kind of hard to explain, but when Invoke has a sub-process open that intends to be fully interactive and utilize all of readline, the way Invoke handles this is... sub-par. Instead of instant quick responses to movement commands, they all seem to be "delayed" by one (e.g., when moving left one, the cursor won't move; if you move left again, the cursor will move over one character to the left, even though it should be two characters over). However, the second you send characters, the cursor's position is updated instantly and is correct. All of this makes things like, running your tests with an auto-PDB on failure via Invoke, very hard to do it.

It's best demonstrated via video: https://asciinema.org/a/enggvan6f8c1c14b76g9ztxh0

The video will also show that Fabric managed to handle this just fine, so I believe it can be done, I'm just not sure what's missing.

Here's a full GH repo that reproduces the entire thing and gives you information on the whole thing: https://github.com/hjc1710/invoke-readline-bug

Some other information:

* This happens anywhere advanced readline is expected to be used, from `git tag -a` to `python` to `vim`.
* This does not appear to be Linux specific, as OSX co-workers have shown me this as well.
    * As an aside, I am running Linux Mint running Raring (13.04).
* This has been present since at least Invoke v0.11 and is still present in v0.13.
* Python version: 2.7.4, but I've also seen it on 2.7.10. I have not tested this on Python 3.

However, even with this... I still love Invoke! Ditching Fabric's core was sooooo worth it for how powerful Invoke is and how good it is at parsing arguments, this is the final little stickler for me.

Thanks for the great tool! Let me know if you have questions or anything isn't clear!

**Comment by bitprophet** [comment] 2016-06-17 21:24
Thanks for the note & details! Nontrivial interactive stuff like readline, vim etc is a known weakness (one that I do want to get fixed sometime), see #58 - in fact I think this can be considered a dupe of that ticket so I'm gonna roll it into there.

Re: Fabric handling it, did you mean `local` or `run`? Fabric's `local` was "just `subprocess`" so it behaved better on this front, but was significantly worse an API (no ability to intercept the streams and capture at the same time, etc). If you meant `run` then that is more interesting because `run`, at a high level, is similar to Invoke's `run` re: all streams being directly handled.

**Closed by bitprophet** 2016-06-17 21:24 UTC

**Comment by hjc1710** [comment] 2016-06-17 21:28
Excellent! Yea I saw #58 and it was the closest thing I could find to a dupe, but wasn't quite sure if it was an exact dupe, mostly since #58 talks heavily about streams, keeping them separated, and special edge cases that occur when `pty=False` is used. So, I figured, let's just open a new ticket and provide info! More than happy with merging the two and I'll subscribe to #58 :smile:.

I'm really glad that this is on your radar and is something you intend to fix. Answers to your question will be given in #58, since that's more appropriate.

Thanks @bitprophet, you the man!
