### ISSUE TITLE
Error in program.run(namespace=custom_namespace)

### ISSUE THREAD

**Issue by vlad-dragos** [pyinvoke/invoke#392] opened 2016-09-18 13:40 UTC
When running Invoke as external library with a custom namespace you get the following error:

```
Traceback (most recent call last):
  File "/.venv/lib/python3.5/site-packages/invoke/vendor/lexicon/attribute_dict.py", line 4, in __getattr__
    return self[key]
  File "/.venv/lib/python3.5/site-packages/invoke/vendor/lexicon/alias_dict.py", line 80, in __getitem__
    return self._handle(key, None, single, multi, unaliased)
  File "/.venv/lib/python3.5/site-packages/invoke/vendor/lexicon/alias_dict.py", line 62, in _handle
    return unaliased(self, key, value)
  File "/.venv/lib/python3.5/site-packages/invoke/vendor/lexicon/alias_dict.py", line 74, in unaliased
    def unaliased(d, key, value): return super(AliasDict, d).__getitem__(key)
KeyError: 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 14, in <module>
    sys.exit(program.run())
  File "/.venv/lib/python3.5/site-packages/invoke/program.py", line 269, in run
    self._parse(argv)
  File "/.venv/lib/python3.5/site-packages/invoke/program.py", line 352, in _parse
    if self.args.list.value:
  File "/.venv/lib/python3.5/site-packages/invoke/vendor/lexicon/__init__.py", line 23, in __getattr__
    return super(Lexicon, self).__getattr__(key)
  File "/.venv/lib/python3.5/site-packages/invoke/vendor/lexicon/attribute_dict.py", line 7, in __getattr__
    raise AttributeError(key)
AttributeError: list
```

I traced the error to the fact that `--list` is a task specific argument and not a core one. I moved it from `Program.task_args()` to `Program.core_args()` and everything seems to work ok.  

Should I make a PR with this "fix"?

**Comment by vlad-dragos** [comment] 2016-09-18 14:06
Ok so the problem seems to come from here https://github.com/pyinvoke/invoke/blob/master/invoke/program.py#L434

Is there a reason for having that `if`?

**Comment by bitprophet** [comment] 2016-09-19 16:58
Thanks for the report! The actual error itself sounds like it's #288, especially given your fix. That is now months and months old but still intended for fixing sometime. But see below.

To answer your question: the `if` is there because when Program's `namespace` functionality was added, we assumed that this use case of "be a self-contained binary instead of a rebranded task runner" wouldn't need/want to have `--list`, and would also want to define its own `--help` (since that is where "normal" CLI apps tend to put their list of subcommands :)).

If you can provide more info on exactly how you're intending to use Invoke-as-another-binary (as well as the actual code you've got, if you want to share) it might make it clearer whether that assumption I just noted, is actually appropriate or not.

This functionality is pretty new & not frequently used so I'd expect it to require more tweaks before it feels 1.0-ready. That's one reason #288 is in the next feature release milestone and not a bugfix. (Though I'd like to pop out 0.14 sometime soon either way, I'm actually close to finishing a long-suffering feature set that will require such a release.)

**Comment by vlad-dragos** [comment] 2016-09-20 06:12
Well I have some scripts that I want to bundle together and Invoke seems to be the perfect for it. I moved all my scripts into a Python module, refactored them to be Invoke tasks, I created the following file to act as the entry point and then I simlinked it to `/usr/local/bin/`. 

```
import os
import sys
# os.environ.setdefault("INVOKE_DEBUG", "1")

from invoke import Program    
from tasks import namespace

if __name__ == '__main__':
    program = Program(namespace=namespace)
    sys.exit(program.run())
```

A more broad use case would be that you could bundle up tasks and redistribute them. Let's say you have a custom web app and you have administrative tasks like migrating the database or running the unit tests, you could use Invoke to create something like Django's `manage.py`. This way you have a clean way of sharing the project between developers and Invoke acts as the `task framework`.

**Comment by matheo** [comment] 2016-09-26 05:07
It would be good if that error is fixed and we could use a basic program.
I'm using the development version and there are some issues with simple tasks it seems :(

I've installed `invoke` with:
```
pip3 install -e git+https://github.com/pyinvoke/invoke#egg=invoke
```
and my task is throwing an error not getting the context param:
```
'task.name' did not receive all required positional arguments!
```
a problem with namespaces too? or what can i do? TIA

**Comment by matheo** [comment] 2016-10-04 05:08
I solved my issue uninstalling and making a clean dev install, weird stuff.
Keep up the good work and thanks a ton!

**Comment by bitprophet** [comment] 2016-11-30 21:42
Not sure why I didn't close this, it definitely seems covered under #288 as mentioned.

**Closed by bitprophet** 2016-11-30 21:42 UTC
