### ISSUE TITLE
CTRL+C/Sigkill stopped working

### ISSUE THREAD

**Issue by noirbizarre** [pyinvoke/invoke#327] opened 2016-02-12 11:42 UTC
Sigkill/CTRL+C does not kill the process any more in 0.12.2.

I can reproduce this with any long running process waiting for a sigkill to end.
I think this is the same issue as #315 and that it's not Docker related.

**Comment by svetlyak40wt** [comment] 2016-02-14 19:40
I've checked, and Ctrl+C works perfectly in invoke==0.11.1.

**Comment by svetlyak40wt** [comment] 2016-02-15 06:23
Sorry, I've rechecked, how 0.11.1 works. It exists on Ctrl-C, but child process remains alive.

I've downgraded to the 0.10.1 and now seems everything works fine there.

**Comment by noirbizarre** [comment] 2016-02-15 17:27
Yep, it worked fine in 0.10.1

**Comment by bitprophet** [comment] 2016-02-17 23:36
This seems like a duplicate of #315.

**Closed by bitprophet** 2016-02-17 23:36 UTC

**Comment by svetlyak40wt** [comment] 2016-06-07 16:40
Seems, neither this nor #315 issues are solved but both are closed. Why?

**Comment by bitprophet** [comment] 2016-06-11 18:26
See #152, this is out in 0.13.

**Comment by svetlyak40wt** [comment] 2016-06-13 12:40
Ok, thank you!
